
# Colors
# class                 border  backgr. text    indicator child_border

client.focused          #d8dee9 #d8dee9 #2e3440 #d8dee9 #d8dee9
client.focused_inactive #e5e9f0 #e5e9f0 #3b4252 #e5e9f0 #e5e9f0

client.unfocused        #4c566a #4c566a #eceff4 #4c566a #4c566a
client.urgent           #bf616a #bf616a #EBDBB2 #bf616a #bf616a

client.placeholder      #000000 #0c0c0c #d8dee9 #000000 #0c0c0c
client.background       #ffffff

exec_always --no-startup-id feh --bg-fill ~/.local/share/wallpapers/nord/dark/wallpaper_dark.png
