set $bg0h          #f9f5d7
set $bg0           #fbf1c7
set $bg0s          #f2e5bc
set $bg1           #ebdbb2
set $bg2           #d5c4a1
set $bg3           #bdae93
set $bg4           #a89984
set $fg0           #282828
set $fg1           #3c3836
set $fg2           #504945
set $fg3           #665c54
set $fg4           #7c6f64
set $red0          #cc241d
set $green0        #98971a
set $yellow0       #d79921
set $blue0         #458588
set $purple0       #b16286
set $aqua0         #689d6a
set $orange0       #d65d0e
set $gray0         #7c6f64
set $red1          #9d0006
set $green1        #79740e
set $yellow1       #b57614
set $blue1         #076678
set $purple1       #8f3f71
set $aqua1         #427b58
set $orange1       #af3a03
set $gray1         #928374

client.focused          $fg0    $fg0    $bg0    $fg0      $fg0
client.focused_inactive $bg2    $bg2    $fg1    $bg2      $bg2
client.unfocused        $bg2    $bg2    $fg0    $bg2      $bg2
client.urgent           $red1   $red1   $bg1    $red1     $red1

exec_always --no-startup-id feh --bg-fill ~/.local/share/wallpapers/Gruvbox/light/wallpaper_light.png
