alias ct='clear'
alias x='exit'
alias mntusb='sudo mount -t vfat /dev/sdb1 /mnt/usb0'
alias untargz='tar -xvzf'
alias untarxz='tar -xvJf'
alias screenfilm='ffmpeg -video_size 1920x1080 -framerate 30 -f x11grab -i :0.0 ~/Videos/screenrecordings/$(date +"%Y-%m-%d_%H-%M-%S").mp4'
alias ls='lsd'
alias cat='batcat'
