print_info() {
    prin ""
    prin ""
    prin "\e[1;38;5;166m$(whoami)\e[0m@\e[1;38;5;166m$(hostname)\e[0m"
    prin "$(color 15)───────────────"
   chassis_type=$(cat /sys/class/dmi/id/chassis_type 2>/dev/null)
    case "$chassis_type" in
        3|4|5|6|7)         chassis_name="Desktop" ;;
        8|9|10|11|14)      chassis_name="Laptop" ;;
        17|18|19|20|21|22|23) chassis_name="Server" ;;
        30|31|32)          chassis_name="Tablet" ;;
        *)                 chassis_name="Unknown" ;;
    esac
    prin "$(color 1)󰾰  " "$chassis_name"
    info "$(color 2)  " model
    info "$(color 3)  " cpu
    info "$(color 4)󰢮  " gpu
    info "$(color 5)󰘅  " distro
    info "$(color 6)  " kernel
    prin ""
    info "$(color 9)󰏖  " packages
    info "$(color 10)󰶙  " shell
    info "$(color 11)  " wm
    info "$(color 12)  " term
    info "$(color 13)  " theme
    info "$(color 14)󰔚  " uptime
    prin ""
    prin "$(color 1)  $(color 2)  $(color 3)  $(color 4)  $(color 5)  $(color 6)  $(color 7)  $(color 15)"
}

title_fqdn="off"

kernel_shorthand="off"

distro_shorthand="off"
os_arch="on"

uptime_shorthand="on"

package_managers="on"

shell_path="off"
shell_version="on"

cpu_brand="on"
cpu_speed="off"
cpu_cores="logical"
cpu_temp="off"

gpu_brand="on"
gpu_type="all"

colors=(distro)
bold="on"
underline_enabled="on"
underline_char="-"

separator="  "

block_range=(0 15)
color_blocks="on"
block_width=3
block_height=1
col_offset="auto"

bar_char_elapsed="-"
bar_char_total="="
bar_border="on"
bar_length=15
bar_color_elapsed="distro"
bar_color_total="distro"
cpu_display="off"
memory_display="off"
battery_display="off"
disk_display="off"

image_backend="ascii"
image_source="${HOME}/.config/neofetch/art.txt"
ascii_distro="auto"
ascii_colors=(distro)
ascii_bold="on"

gap=3
yoffset=3
xoffset=3

image_loop="off"
thumbnail_dir="${XDG_CACHE_HOME:-${HOME}/.cache}/thumbnails/neofetch"
crop_mode="normal"
crop_offset="center"
image_size="auto"
background_color=
stdout="off"
memory_percent="off"
memory_unit="mib"
refresh_rate="off"
gtk_shorthand="off"
gtk2="on"
gtk3="on"
public_ip_host="http://ident.me"
public_ip_timeout=2
de_version="on"
disk_show=('/')
disk_subtitle="mount"
disk_percent="on"
music_player="auto"
song_format="%artist% - %album% - %title%"
song_shorthand="off"
mpc_args=()
