[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[bell.command]
args = ["-c", "paplay ~/.config/alacritty/pop.wav"]
program = "sh"

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[scrolling]
multiplier = 1

[general]
import = ["/home/migueltfd/.config/alacritty/colors.toml"]
